### ISSUE TITLE
Neutron Drive as Google Drive Add On

### ISSUE THREAD

**Issue by RoyiAvital** [pizzapanther/Super-Neutron-Drive#69]
Hello,
Could you make Neutron as a Google Docs Add On (Like [StackEdit](https://github.com/benweet/stackedit))?

Some people don't want extension to be installed.
Moreover Google Drive is missing some kind of Code Editor.

Thank You.

**Comment by pizzapanther** [comment]
If don't want to install anything you can use the old version of Neutron Drive: https://www.neutrondrive.com/edit

There are no plans to add this to the new version because you can't get the permissions needed for newer features without installing the app.

**Comment by RoyiAvital** [comment]
What permission are needed?

Can I stay anonymous?
Namely, you won't have my email address?

Thank You.

**Comment by pizzapanther** [comment]
The permissions I'm talking about are things like being able to access the local file system for local file editing. Actually email isn't used right now. The permissions used are start at: https://github.com/pizzapanther/Super-Neutron-Drive/blob/master/chrome-app/manifest.json#L21

I do think Google lets you install apps anonymously now but I haven't tried it yet.
