### ISSUE TITLE
Can't sign in to google drive

### ISSUE THREAD

**Issue by alkopop79** [pizzapanther/Super-Neutron-Drive#75]
I should have tried it first, then pay... When I chose to save code to Google Drive and add account, I get the option to add my account but cannot actually type anything. Can I get a refund?

**Comment by pizzapanther** [comment]
send your email you used to sign up to help@neutrondrive.com. But also some google service have been down today, so you should retry and it might work.

**Comment by alkopop79** [comment]
Nothing about the refund ...

**Comment by pizzapanther** [comment]
If you can't follow simple directions then don't whine like a baby.
